### ISSUE TITLE
Heavy website

### ISSUE THREAD

**Issue by Tejas-Nanaware** [maniac-tech/CodeStrike#23]
# Website needs to be optimized
1. It puts load which has to be reduced via server side scripting.
2. Try to minimize the load.

![image](https://user-images.githubusercontent.com/21222179/27169660-66ea412e-51c8-11e7-9bdf-47188c96a39f.png)

**Comment by maniac-tech** [comment]
Withe current updates, we have reduced the loading duration from 60s to 30s.
We'll see if we can reduce it more.
