### ISSUE TITLE
Minor fixes

### ISSUE THREAD

**Issue by Prashant-mahajan** [maniac-tech/CodeStrike#4]
1. CodeStrike & LinkedIn profile not linked
2. Navigation through navbar is not working properly

**Comment by maniac-tech** [comment]
What issues dis you find with the navigation bar?
Specifications would help

**Comment by Prashant-mahajan** [comment]
When you click on 'About us' or 'Events' it should take you to respective section of the website but instead it does nothing. 
Also, one new correction: 
link to About us & work from team.php page is broken.

**Comment by maniac-tech** [comment]
Your concerned issues in regards to the navigation bar have been corrected.
